import { env } from "cloudflare:workers";
import { SEED_PRODUCTS } from "./menu";
import { chinaDayStart, orderQuery, merchantAnalytics } from "./operations";
import { pickupWindow, validPickup, pickupBucket, kitchenReceipt, feieReceipt, contactPhone, categoryOrder } from "./pickup";
const M="demo-stall";const encoder=new TextEncoder();
type Row=Record<string,any>;
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export function settings():Record<string,any>{return env as any}
export function database():D1Database{const db=(env as any).DB;if(!db)throw new ApiError(503,"订单服务暂时不可用，请稍后重试");return db}
export function config(name:string){return String(settings()[name]??process.env[name]??"")}
export async function sha(s:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(s)))].map(v=>v.toString(16).padStart(2,"0")).join("")}
export async function same(a:string,b:string){return !!a&&!!b&&(await sha(a))===(await sha(b))}
export function tenantId(req:Request){const id=new URL(req.url).searchParams.get("tenant")??"demo-stall";if(!/^[a-z0-9][a-z0-9-]{2,39}$/.test(id))throw new ApiError(400,"租户编号格式无效");return id}
export async function requireKey(req:Request,role:"merchant"|"service",M="demo-stall"){
 const input=req.headers.get("x-admin-key")??"";
 if(role==="service"){if(!(await same(input,config("SERVICE_ADMIN_KEY"))))throw new ApiError(401,"超管密钥不正确");return;}
 const m=await merchant(M);const valid=m.login_key_hash?await same(await sha(input),m.login_key_hash):M==="demo-stall"&&await same(input,config("MERCHANT_ADMIN_KEY"));
 if(!input||!valid)throw new ApiError(401,"店家密钥与租户不匹配，请重新输入");
}
export async function merchantLogin(req:Request){
 await seed();const input=req.headers.get("x-admin-key")??"";
 if(!input||input.length>200||await same(input,config("SERVICE_ADMIN_KEY")))throw new ApiError(401,"店家密钥不正确");
 const matches=await database().prepare("SELECT id FROM merchants WHERE login_key_hash=? LIMIT 2").bind(await sha(input)).all<Row>();
 if(matches.results.length===1)return merchantData(matches.results[0].id);
 if(!matches.results.length&&await same(input,config("MERCHANT_ADMIN_KEY"))){const m=await merchant();if(!m.login_key_hash)return merchantData(m.id);}
 throw new ApiError(401,"店家密钥不正确");
}

function b64(s:string){return btoa(s).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
function un64(s:string){return atob(s.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(s.length/4)*4,"="))}
async function mac(s:string){const secret=config("LICENSE_SECRET");if(secret.length<24)throw new ApiError(503,"服务授权尚未配置，请联系服务商");const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign("HMAC",key,encoder.encode(s))))) }
export async function issueLicense(expires:number,M="demo-stall"){const p=b64(JSON.stringify({v:1,merchant:M,expires,nonce:crypto.randomUUID()}));return p+"."+await mac(p)}
export async function verifyLicense(token:string,M="demo-stall"){try{const [p,s,extra]=token.split(".");if(extra||!p||!s||!(await same(s,await mac(p))))return null;const data=JSON.parse(un64(p));return data.v===1&&data.merchant===M&&Number.isInteger(data.expires)?data:null}catch{return null}}
export function monthAfter(now=Date.now()){const d=new Date(now);const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.getTime()}
export async function seed(){const db=database();if(await db.prepare("SELECT id FROM merchants WHERE id=?").bind(M).first())return;const now=Date.now(),expires=monthAfter(now),token=await issueLicense(expires,M);await db.batch([db.prepare("INSERT OR IGNORE INTO merchants (id,name,license_token,license_expires,suspended,printer_online,capacity,payment_label,updated_at) VALUES (?,?,?,?,0,1,6,?,?)").bind(M,"东北烤冷面",token,expires,"示例商户 · 未配置真实收款码",now),...SEED_PRODUCTS.map((p)=>db.prepare("INSERT OR IGNORE INTO products (id,merchant_id,name,category,price,active,sort,updated_at) VALUES (?,?,?,?,?,1,?,?)").bind(p.id,M,p.name,p.category,p.price,p.sort,now))]);}
export async function merchant(M="demo-stall"){await seed();const m=await database().prepare("SELECT * FROM merchants WHERE id=?").bind(M).first<Row>();if(!m)throw new ApiError(404,"店家不存在，请检查租户编号");return m}
export async function licenseStatus(m:Row){const data=await verifyLicense(m.license_token,m.id);return {valid:!!data&&!m.suspended&&data.expires===m.license_expires&&data.expires>Date.now(),expiresAt:m.license_expires,suspended:!!m.suspended,signatureValid:!!data};}
export async function expireReservations(){const now=Date.now();await database().prepare("UPDATE orders SET status='expired',updated_at=? WHERE status='reserved' AND payment_state='unconfirmed' AND created_at<?").bind(now,now-15*60_000).run()}
export function pickupSlots(){const now=Date.now();const start=Math.ceil((now+10*60_000)/(10*60_000))*10*60_000;return Array.from({length:12},(_,i)=>start+i*10*60_000)}
export function chinaTime(n:number){return new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(n))}
export async function catalog(M="demo-stall"){const m=await merchant(M);await expireReservations();const list=await database().prepare("SELECT * FROM products WHERE merchant_id=? ORDER BY sort").bind(M).all<Row>();const slots=pickupSlots();const used=await database().prepare("SELECT pickup_at,SUM(quantity) AS used FROM orders WHERE merchant_id=? AND status NOT IN ('cancelled','expired') AND pickup_at>=? GROUP BY pickup_at").bind(M,slots[0]).all<Row>();return {merchant:{id:M,name:m.name,subtitle:m.subtitle,description:m.description,accent:m.accent,heroImage:m.hero_image,contactPhone:m.contact_phone,categoryOrder:JSON.parse(m.category_order||"[]"),paymentLabel:m.payment_label,paymentQr:m.payment_qr},license:await licenseStatus(m),products:list.results.filter(p=>p.active),slots:slots.map(at=>({at,label:chinaTime(at),remaining:Math.max(0,m.capacity-Number(used.results.find(r=>r.pickup_at===at)?.used??0))})),pickupWindow:pickupWindow(),demoMode:true};}
function receipt(order:Row){return kitchenReceipt(order)}
export async function runPrintJobs(M="demo-stall"){const db=database(),m=await merchant(M);if(!m.printer_online)return;const jobs=await db.prepare("SELECT * FROM print_jobs WHERE status='queued' AND order_id IN (SELECT id FROM orders WHERE merchant_id=?) ORDER BY created_at LIMIT 20").bind(M).all<Row>();for(const job of jobs.results){const lock=await db.prepare("UPDATE print_jobs SET status='sending',attempts=attempts+1,updated_at=? WHERE id=? AND status='queued'").bind(Date.now(),job.id).run();if(!lock.meta.changes)continue;if(config("PRINTER_MODE")!=="feie"){await db.prepare("UPDATE print_jobs SET status='demo_printed',updated_at=? WHERE id=?").bind(Date.now(),job.id).run();continue}try{if(M!=="demo-stall")throw new Error("请为此租户单独绑定打印账户与设备");if(!config("FEIE_USER")||!config("FEIE_UKEY")||!config("FEIE_SN"))throw new Error("真机配置不完整");const stime=String(Math.floor(Date.now()/1000));const value=config("FEIE_USER")+config("FEIE_UKEY")+stime;const sig=[...new Uint8Array(await crypto.subtle.digest("SHA-1",encoder.encode(value)))].map(v=>v.toString(16).padStart(2,"0")).join("");const content=feieReceipt(job.receipt);const result=await fetch("https://api.feieyun.cn/Api/Open/printMsg",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({user:config("FEIE_USER"),stime,sig,apiname:"Open_printMsg",sn:config("FEIE_SN"),content,times:"1"}),signal:AbortSignal.timeout(8000)});const data:any=await result.json();if(data.ret!==0){await db.prepare("UPDATE print_jobs SET status='failed',error=?,updated_at=? WHERE id=?").bind("云打印拒绝请求，请检查设备与账户",Date.now(),job.id).run();continue}await db.prepare("UPDATE print_jobs SET status='submitted',provider_id=?,updated_at=? WHERE id=?").bind(String(data.data),Date.now(),job.id).run();}catch{await db.prepare("UPDATE print_jobs SET status='unknown',error='请求结果不明，核对设备后再处理，禁止自动重复出单',updated_at=? WHERE id=?").bind(Date.now(),job.id).run()}}}
export async function createOrder(body:Row,M="demo-stall"){const m=await merchant(M);await expireReservations();if(!body.idempotencyKey||!body.accessToken||!Array.isArray(body.items)||body.items.length>35)throw new ApiError(400,"订单信息不完整");if(!/^[A-Za-z0-9_-]{20,100}$/.test(body.accessToken)||!/^[A-Za-z0-9_-]{20,100}$/.test(body.idempotencyKey))throw new ApiError(400,"订单凭证无效");const requestHash=await sha(JSON.stringify({...body,accessToken:undefined}));const existing=await database().prepare("SELECT * FROM orders WHERE idempotency_key=?").bind(body.idempotencyKey).first<Row>();if(existing){if(existing.merchant_id!==M||existing.request_hash!==requestHash||existing.access_hash!==await sha(body.accessToken))throw new ApiError(409,"该订单凭证已被使用，请重新确认");return await readOrder(existing.id,body.accessToken,M)}
const lic=await licenseStatus(m);if(!lic.valid)throw new ApiError(403,"商户服务授权已到期或暂停，暂不接收新预约；已有订单仍可处理");
const pickup=Number(body.pickupAt);if(!validPickup(pickup))throw new ApiError(400,"预约时间已失效，请重新选择");if(!["不辣","微辣","中辣","特辣"].includes(body.spice))throw new ApiError(400,"请选择有效口味");const note=String(body.note??"").trim(),alias=String(body.alias??"").trim();if(note.length>120||alias.length>20)throw new ApiError(400,"备注或称呼过长");const ids=new Set();const rows:Row[]=[];let quantity=0,total=0;for(const item of body.items){if(!item||ids.has(item.id)||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>6)throw new ApiError(400,"餐品数量无效");ids.add(item.id);const p=await database().prepare("SELECT * FROM products WHERE id=? AND merchant_id=?").bind(item.id,M).first<Row>();if(!p||!p.active)throw new ApiError(409,"有商品已下架，请重新选餐");if(p.price!==item.expectedPrice)throw new ApiError(409,"商品价格已更新，请重新确认金额");rows.push({id:p.id,name:p.name,price:p.price,quantity:item.quantity,version:p.updated_at,category:p.category});total+=p.price*item.quantity;if(p.category!=="单独加料")quantity+=item.quantity;}
if(quantity<1||quantity>6||total>100_000)throw new ApiError(400,"每次请预约 1—6 份主餐，加料需搭配主餐");const bucket=pickupBucket(pickup);const id=crypto.randomUUID(),accessHash=await sha(body.accessToken),now=Date.now(),code=Math.random().toString(36).slice(2,8).toUpperCase();const order={id,pickup_code:code,pickup_at:pickup,items:JSON.stringify(rows),total,spice:body.spice,note,alias};const guards=rows.map(()=>"EXISTS (SELECT 1 FROM products WHERE id=? AND merchant_id=? AND active=1 AND price=? AND updated_at=?)").join(" AND ");const sql=`INSERT OR IGNORE INTO orders (id,merchant_id,idempotency_key,request_hash,access_hash,pickup_code,pickup_at,quantity,total,items,note,spice,alias,status,payment_state,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,'reserved','unconfirmed',?,? WHERE (SELECT COALESCE(SUM(quantity),0) FROM orders WHERE merchant_id=? AND pickup_at>=? AND pickup_at<? AND status NOT IN ('cancelled','expired'))+? <= (SELECT capacity FROM merchants WHERE id=? AND suspended=0 AND license_expires>?) AND ${guards}`;
const args:any[]=[id,M,body.idempotencyKey,requestHash,accessHash,code,pickup,quantity,total,JSON.stringify(rows),note,body.spice,alias,now,now,M,bucket.start,bucket.end,quantity,M,now,...rows.flatMap(p=>[p.id,M,p.price,p.version])];await database().batch([database().prepare(sql).bind(...args),database().prepare("INSERT OR IGNORE INTO print_jobs (id,order_id,status,receipt,attempts,created_at,updated_at) SELECT ?,id,'queued',?,0,?,? FROM orders WHERE id=?").bind(crypto.randomUUID(),receipt(order),now,now,id)]);const saved=await database().prepare("SELECT id FROM orders WHERE idempotency_key=?").bind(body.idempotencyKey).first<Row>();if(!saved)throw new ApiError(409,"该时段已满或商品已变化，请重新选时段并确认菜单");await runPrintJobs(M);return await readOrder(saved.id,body.accessToken,M);}
export async function readOrder(id:string,token:string,M="demo-stall"){const row=await database().prepare("SELECT * FROM orders WHERE id=? AND access_hash=? AND merchant_id=?").bind(id,await sha(token),M).first<Row>();if(!row)throw new ApiError(404,"未找到这笔预约，请使用原下单页面");const print=await database().prepare("SELECT status,receipt,error FROM print_jobs WHERE order_id=?").bind(id).first();return {...row,access_hash:undefined,idempotency_key:undefined,request_hash:undefined,items:JSON.parse(row.items),print};}
export async function merchantData(M="demo-stall") {
 const m=await merchant(M);await expireReservations();const now=Date.now(),start=chinaDayStart(now),end=start+86400000;
 const [products,orders,jobs,sales]=await Promise.all([
  database().prepare("SELECT * FROM products WHERE merchant_id=? ORDER BY sort").bind(M).all<Row>(),
  database().prepare("SELECT * FROM orders WHERE merchant_id=? ORDER BY CASE WHEN status IN ('reserved','paid','ready','payment_review') THEN 0 ELSE 1 END, pickup_at ASC, created_at DESC LIMIT 100").bind(M).all<Row>(),
  database().prepare("SELECT * FROM print_jobs WHERE order_id IN (SELECT id FROM orders WHERE merchant_id=?) ORDER BY created_at DESC LIMIT 100").bind(M).all<Row>(),
  database().prepare("SELECT merchant_id,created_at,pickup_at,status,payment_state,total,items FROM orders WHERE merchant_id=? AND payment_state='merchant_confirmed' AND status IN ('paid','ready','completed') AND ((created_at>=? AND created_at<?) OR (pickup_at>=? AND pickup_at<?))").bind(M,start,end,start,end).all<Row>()
 ]);
 return {merchant:{...m,license_token:undefined,login_key_hash:undefined,categoryOrder:JSON.parse(m.category_order||"[]")},license:await licenseStatus(m),products:products.results,analytics:merchantAnalytics(sales.results.map(o=>({...o,items:JSON.parse(o.items)})),M,now),orders:orders.results.map(o=>({...o,access_hash:undefined,request_hash:undefined,idempotency_key:undefined,items:JSON.parse(o.items),print:jobs.results.find(p=>p.order_id===o.id)}))};
}
export function imageData(value:unknown){
 if(value===undefined||value===null||value==="")return null;
 if(typeof value!=="string"||value.length>420_000)throw new ApiError(400,"图片过大，请压缩到300KB以内");
 const match=/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);if(!match)throw new ApiError(400,"图片仅支持JPG、PNG或WebP");
 let raw;try{raw=atob(match[2]);}catch{throw new ApiError(400,"图片内容无效");}
 const valid=match[1]==="jpeg"?raw.startsWith("\xff\xd8\xff"):match[1]==="png"?raw.startsWith("\x89PNG\r\n\x1a\n"):raw.startsWith("RIFF")&&raw.slice(8,12)==="WEBP";
 if(!valid)throw new ApiError(400,"图片内容与格式不符");return value;
}
export async function saveProduct(body:Row,M="demo-stall"){
 const name=String(body.name??"").trim(),category=String(body.category??"").trim(),description=String(body.description??"").trim(),price=Number(body.price);
 if(!name||name.length>60||!category||category==="全部"||category.length>30||description.length>160||!Number.isInteger(price)||price<0||price>100_000||typeof body.active!=="boolean")throw new ApiError(400,"请填写有效名称、分类和价格");
 const image=imageData("imageData" in body?body.imageData:body.image_data);
 if(body.id){const saved=await database().prepare("UPDATE products SET name=?,category=?,price=?,active=?,description=?,image_data=?,updated_at=? WHERE id=? AND merchant_id=?").bind(name,category,price,body.active?1:0,description,image,Date.now(),body.id,M).run();if(!saved.meta.changes)throw new ApiError(404,"此租户没有该商品");}
 else await database().prepare("INSERT INTO products (id,merchant_id,name,category,price,active,description,image_data,sort,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind("custom-"+crypto.randomUUID(),M,name,category,price,body.active?1:0,description,image,Date.now(),Date.now()).run();
 return merchantData(M);
}
export async function saveProfile(body:Row,M="demo-stall"){
 const name=String(body.name??"").trim(),subtitle=String(body.subtitle??"").trim(),description=String(body.description??"").trim(),accent=String(body.accent??"");
 if(!name||name.length>60||subtitle.length>80||description.length>160||!["#ea531a","#0f766e","#2563eb","#7c3aed","#be123c","#4338ca"].includes(accent))throw new ApiError(400,"店铺名称或展示内容无效");
 const image=imageData("heroImage" in body?body.heroImage:body.hero_image);let phone,categories;try{phone=contactPhone(body.contactPhone);categories=categoryOrder(body.categoryOrder);}catch(e){throw new ApiError(400,(e as Error).message);}
 await database().prepare("UPDATE merchants SET name=?,subtitle=?,description=?,accent=?,hero_image=?,contact_phone=?,category_order=?,updated_at=? WHERE id=?").bind(name,subtitle,description,accent,image,phone,JSON.stringify(categories),Date.now(),M).run();return merchantData(M);
}
export async function heartbeat(M="demo-stall"){
 const now=Date.now();await database().prepare("UPDATE merchants SET last_heartbeat=? WHERE id=?").bind(now,M).run();
 const m=await merchant(M);return {receivedAt:now,intervalSeconds:20,offlineAfterSeconds:70,license:await licenseStatus(m)};
}
export function heartbeatState(m:Row){const last=Number(m.last_heartbeat)||0;return {lastSeen:last||null,online:!!last&&Date.now()-last<70_000,ageSeconds:last?Math.max(0,Math.floor((Date.now()-last)/1000)):null,source:"店家工作台",offlineAfterSeconds:70};}
export async function orderAction(body:Row,M="demo-stall"){const o=await database().prepare("SELECT * FROM orders WHERE id=? AND merchant_id=?").bind(body.id,M).first<Row>();if(!o)throw new ApiError(404,"订单不存在");let next=o.status,payment=o.payment_state;if(body.action==="confirm_payment"){if(!["reserved","expired","payment_review","paid"].includes(o.status))throw new ApiError(409,"该订单当前不能确认收款");payment="merchant_confirmed";next=o.status==="expired"?"payment_review":"paid";}else if(body.action==="ready"){if(o.status!=="paid")throw new ApiError(409,"先核对收款，再标记餐品做好");next="ready";}else if(body.action==="picked_up"){if(o.status!=="ready")throw new ApiError(409,"请先标记餐品做好");next="completed";}else if(body.action==="cancel"){if(o.payment_state!=="unconfirmed"||!["reserved","expired"].includes(o.status))throw new ApiError(409,"已收款订单请先与顾客处理退款，不可直接取消");next="cancelled";}else throw new ApiError(400,"操作无效");await database().prepare("UPDATE orders SET status=?,payment_state=?,updated_at=? WHERE id=? AND status=? AND payment_state=?").bind(next,payment,Date.now(),o.id,o.status,o.payment_state).run();return merchantData(M);}
export async function serviceData(M="demo-stall"){
 const m=await merchant(M);await expireReservations();const [log,list,totals]=await Promise.all([database().prepare("SELECT * FROM license_events WHERE merchant_id=? ORDER BY created_at DESC LIMIT 20").bind(M).all(),database().prepare("SELECT * FROM merchants ORDER BY id").all<Row>(),database().prepare(`SELECT merchant_id,${summarySQL()} FROM orders GROUP BY merchant_id`).bind(chinaDayStart(),chinaDayStart()).all<Row>()]);
 return {merchant:{id:M,name:m.name,printerOnline:!!m.printer_online,capacity:m.capacity,heartbeat:heartbeatState(m)},license:await licenseStatus(m),events:log.results,tenants:await Promise.all(list.results.map(async(t)=>({id:t.id,name:t.name,license:await licenseStatus(t),heartbeat:heartbeatState(t),stats:totals.results.find(s=>s.merchant_id===t.id)||emptySummary()})))};
}
function emptySummary(){return {totalOrders:0,confirmedOrders:0,confirmedRevenue:0,todayOrders:0,todayRevenue:0,unconfirmedOrders:0,completedOrders:0};}
function summarySQL(){return `COUNT(*) AS totalOrders,COALESCE(SUM(CASE WHEN payment_state='merchant_confirmed' THEN total ELSE 0 END),0) AS confirmedRevenue,SUM(CASE WHEN payment_state='merchant_confirmed' THEN 1 ELSE 0 END) AS confirmedOrders,COALESCE(SUM(CASE WHEN created_at>=? THEN 1 ELSE 0 END),0) AS todayOrders,COALESCE(SUM(CASE WHEN created_at>=? AND payment_state='merchant_confirmed' THEN total ELSE 0 END),0) AS todayRevenue,COALESCE(SUM(CASE WHEN status='reserved' AND payment_state='unconfirmed' THEN 1 ELSE 0 END),0) AS unconfirmedOrders,COALESCE(SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END),0) AS completedOrders`;}
export async function storeOperations(M:string,query:URLSearchParams){
 const m=await merchant(M);await expireReservations();let options;try{options=orderQuery(query);}catch{throw new ApiError(400,"订单查询参数无效");}
 const {page,search,pageSize}=options;
 const where="merchant_id=? AND (?='' OR instr(id,?)>0 OR instr(pickup_code,?)>0)",bindings=[M,search,search,search];
 const [summary,count,rows]=await Promise.all([
  database().prepare(`SELECT ${summarySQL()} FROM orders WHERE merchant_id=?`).bind(chinaDayStart(),chinaDayStart(),M).first<Row>(),
  database().prepare(`SELECT COUNT(*) AS count FROM orders WHERE ${where}`).bind(...bindings).first<Row>(),
  database().prepare(`SELECT id,merchant_id,pickup_code,pickup_at,quantity,total,items,note,spice,alias,status,payment_state,created_at,updated_at,(SELECT status FROM print_jobs WHERE order_id=orders.id LIMIT 1) AS print_status FROM orders WHERE ${where} ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?`).bind(...bindings,pageSize,(page-1)*pageSize).all<Row>()
 ]);
 return {merchant:{id:M,name:m.name},summary:{...emptySummary(),...summary},orders:rows.results.map(o=>({...o,items:JSON.parse(o.items)})),pagination:{page,pageSize,total:Number(count?.count||0),search}};
}
export async function createTenant(body:Row,M="demo-stall"){
 const id=String(body.id??"").trim(),name=String(body.name??"").trim();if(!/^[a-z0-9][a-z0-9-]{2,39}$/.test(id)||!name||name.length>60)throw new ApiError(400,"租户编号须为3—40位小写字母、数字或横线，名称不能为空");
 if(await database().prepare("SELECT id FROM merchants WHERE id=?").bind(id).first())throw new ApiError(409,"这个租户编号已存在");
 const key="shop-"+crypto.randomUUID()+crypto.randomUUID().slice(0,8),now=Date.now(),token=await issueLicense(0,id);
 await database().prepare("INSERT INTO merchants (id,name,license_token,license_expires,suspended,printer_online,capacity,payment_label,login_key_hash,updated_at) VALUES (?,?,?,0,0,1,6,?,?,?)").bind(id,name,token,"示例商户 · 未配置真实收款码",await sha(key),now).run();
 return {...await serviceData(M),createdTenant:{id,name,key}};
}
export async function serviceAction(body:Row,M="demo-stall"){const m=await merchant(M);const now=Date.now();if(body.action==="issue"||body.action==="set_expiry"){const expires=body.action==="set_expiry"?Number(body.expiresAt):monthAfter(Math.max(now,m.license_expires));if(!Number.isSafeInteger(expires)||expires<=now||expires>now+5*366*24*60*60_000)throw new ApiError(400,"到期时间需在现在之后、五年以内");const token=await issueLicense(expires,M);await database().batch([database().prepare("UPDATE merchants SET license_token=?,license_expires=?,suspended=0,updated_at=? WHERE id=?").bind(token,expires,now,M),database().prepare("INSERT INTO license_events (id,merchant_id,kind,expires_at,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),M,body.action,expires,now)]);return {...await serviceData(M),issuedLicense:token};}if(body.action==="expire"){const expires=now-1,token=await issueLicense(expires,M);await database().batch([database().prepare("UPDATE merchants SET license_token=?,license_expires=?,updated_at=? WHERE id=?").bind(token,expires,now,M),database().prepare("INSERT INTO license_events (id,merchant_id,kind,expires_at,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),M,"demo_expire",expires,now)]);}else if(body.action==="suspend"||body.action==="resume"){await database().prepare("UPDATE merchants SET suspended=?,updated_at=? WHERE id=?").bind(body.action==="suspend"?1:0,now,M).run();}else if(body.action==="printer"){if(typeof body.online!=="boolean")throw new ApiError(400,"设备状态无效");await database().prepare("UPDATE merchants SET printer_online=?,updated_at=? WHERE id=?").bind(body.online?1:0,now,M).run();if(body.online)await runPrintJobs(M);}else if(body.action==="capacity"){if(!Number.isInteger(body.capacity)||body.capacity<1||body.capacity>30)throw new ApiError(400,"每时段名额需为 1—30 份");await database().prepare("UPDATE merchants SET capacity=?,updated_at=? WHERE id=?").bind(body.capacity,now,M).run();}else throw new ApiError(400,"操作无效");return serviceData(M);}
export async function activateLicense(token:string,M="demo-stall"){const data=await verifyLicense(token,M);if(!data||data.expires<=Date.now())throw new ApiError(400,"License 无效、被修改或已经过期");const m=await merchant(M);if(m.suspended)throw new ApiError(403,"商户已被服务商暂停，请联系服务商处理");if(data.expires<m.license_expires)throw new ApiError(409,"不能用旧 License 覆盖更新的授权");await database().prepare("UPDATE merchants SET license_token=?,license_expires=?,updated_at=? WHERE id=?").bind(token,data.expires,Date.now(),M).run();return merchantData(M);}
